development:
  clients:
    default:
      uri: <%= ENV.fetch('MONGODB_URI', 'mongodb://localhost/maslow_development') %>

test:
  clients:
    default:
      uri: <%= ENV.fetch('MONGODB_URI', 'mongodb://localhost/maslow_test') %>
      options:
        max_retries: 1
        retry_interval: 0

production:
  clients:
    default:
      uri: <%= ENV["MONGODB_URI"] %>
