development:
  sessions:
    default:
      uri: <%= ENV.fetch('MONGODB_URI', 'mongodb://localhost/maslow_development') %>

test:
  sessions:
    default:
      uri: <%= ENV.fetch('MONGODB_URI', 'mongodb://localhost/maslow_test') %>
      options:
        max_retries: 1
        retry_interval: 0
